set fallback := true

_default:
    @just --list

# build sd card image
build:
    nix build -o ../../results/gateway --builders "$(just _builders)" .#nixosConfigurations.gateway.config.system.build.sdImage

# flash sd card image (usage: just flash /dev/sdX)
flash device:
    zstdcat ../../results/gateway/sd-image/*.img.zst | sudo dd of={{device}} bs=4M status=progress conv=fsync

# push build closure to binary cache (excludes sd-image)
push:
    nix path-info -r ../../results/gateway | grep -v 'sd-image' | xargs attic push main

# deploy config to running device over SSH
deploy:
    nixos-rebuild switch --flake ".#gateway" --target-host iot@gateway --build-host iot@gateway --use-remote-sudo
